name: AutoGate .NET Deployment

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - uses: microsoft/variable-substitution@v1
        with:
          files: './src/IFCE.AutoGate.API/appsettings.json'
        env:
          "ConnectionStrings.DefaultConnection": ${{ secrets.DB_CONNECTION_STRING }}
        
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - uses: azure/docker-login@v1
        with: 
          login-server: autogate.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          
      - run: |
          docker build . -t autogate.azurecr.io/autogate:${{ github.sha }}
          docker push autogate.azurecr.io/autogate:${{ github.sha }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'autogate-api'
          images: 'autogate.azurecr.io/autogate:${{ github.sha }}'
 
      - name: Azure logout
        run: |
          az logout